// SCME service worker — offline support + safe auto-update.
//
// Strategy: an ATOMIC, versioned precache. On install we download the whole
// app shell into a cache named for CACHE_VERSION; we only ever serve files
// from that one version, so index.html and the css/js it pins by SRI can never
// be mismatched (a stale index.html + fresh app.js would fail the integrity
// check). A new deploy changes CACHE_VERSION, the browser installs the new
// worker in the background, and js/pwa.js offers the user a "Reload" toast —
// nothing swaps out from under an in-progress circuit until they choose.
//
// CACHE_VERSION and PRECACHE below are GENERATED by tools/gen-csp.py from the
// real asset bytes, so any changed file bumps the version automatically. Run
// `python3 tools/gen-csp.py` after editing assets. Do not hand-edit the block.

/* @generated by tools/gen-csp.py — CACHE_VERSION + PRECACHE. Do not edit. */
const CACHE_VERSION = 'scme-22af636459a0';
const PRECACHE = [
  './',
  'css/styles.css',
  'favicon.svg',
  'icons/apple-touch-icon.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'index.html',
  'js/app.js',
  'js/engine/arcingFaultFactor.js',
  'js/engine/asymmetry.js',
  'js/engine/breakerAnalysis.js',
  'js/engine/cable.js',
  'js/engine/cableLibrary.js',
  'js/engine/capacitor.js',
  'js/engine/circuit.js',
  'js/engine/conductorMaterial.js',
  'js/engine/constants.js',
  'js/engine/faultType.js',
  'js/engine/impedance.js',
  'js/engine/load.js',
  'js/engine/motor.js',
  'js/engine/phasor.js',
  'js/engine/sha512.js',
  'js/engine/source.js',
  'js/engine/temperatureCorrection.js',
  'js/engine/threeWindingTransformer.js',
  'js/engine/transformer.js',
  'js/model.js',
  'js/pwa.js',
  'js/schematic.js',
  'js/scmeFile.js',
  'js/scwin/carchive.js',
  'js/scwin/decoder.js',
  'js/scwin/importer.js',
  'js/validation.js',
  'manifest.json',
];
/* @end generated */

// ── Install: fill the versioned cache, then wait. ───────────────────────
// No skipWaiting() here: the fresh worker stays in "waiting" until the user
// accepts the update (pwa.js posts SKIP_WAITING), so we never reload mid-edit.
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_VERSION).then((cache) => cache.addAll(PRECACHE))
  );
});

// ── Activate: drop old versions, take control. ──────────────────────────
self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys.filter((k) => k.startsWith('scme-') && k !== CACHE_VERSION)
          .map((k) => caches.delete(k))
    );
    await self.clients.claim();
  })());
});

// ── Fetch: cache-first from the versioned set; network only for misses. ──
// Everything served in a page load comes from one CACHE_VERSION, so the SRI
// pins in index.html always match. Offline navigations fall back to the shell.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;                       // GET only
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;        // same-origin only
  event.respondWith(handle(req));
});

async function handle(req) {
  const cache = await caches.open(CACHE_VERSION);
  const cached = await cache.match(req, { ignoreSearch: true });
  if (cached) return cached;
  try {
    return await fetch(req);
  } catch (err) {
    if (req.mode === 'navigate') {
      const shell = (await cache.match('index.html')) || (await cache.match('./'));
      if (shell) return shell;
    }
    throw err;
  }
}

// ── The waiting worker activates as soon as the user accepts the update. ─
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});
