#!/usr/bin/env python3
"""Regenerate the Content-Security-Policy and Subresource-Integrity hashes.

SCMEWeb is served with a strict CSP so a tampered file is refused by the
browser instead of run. The policy pins:

  * every INLINE <script> in index.html, by SHA-256, in `script-src`
    (an edited inline script no longer matches and is blocked); and
  * the linked subresources it can protect cross-browser — css/styles.css and
    the js/app.js module entry — with SHA-384 `integrity` (SRI) attributes.

Run this after editing the inline script, css/styles.css, or js/app.js, then
redeploy. It rewrites the integrity="" attributes in index.html and the
_headers file in place. Stdlib only; no build step, no dependencies.

    python3 tools/gen-csp.py          # patch files
    python3 tools/gen-csp.py --check  # verify they are up to date (CI/pre-deploy)

NOTE: the browser hashes the bytes it receives. If the host rewrites assets
(e.g. Cloudflare Rocket Loader or Auto-Minify), the hashes won't match and the
app is blocked — keep those OFF for this site. See README "Security headers".
"""
import base64
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
HEADERS = ROOT / "_headers"

# Subresources protected with SRI (the entry points the browser will verify
# cross-browser; app.js's imported modules are covered by `script-src 'self'`).
SRI_TARGETS = ["css/styles.css", "js/app.js"]

# The security headers that ride alongside the CSP (mirrors the reference site).
STATIC_HEADERS = [
    ("X-Content-Type-Options", "nosniff"),
    ("X-Frame-Options", "DENY"),
    ("Referrer-Policy", "same-origin"),
    ("Cross-Origin-Opener-Policy", "same-origin"),
    ("Strict-Transport-Security", "max-age=2592000; includeSubDomains; preload"),
]


def b64(digest: bytes) -> str:
    return base64.b64encode(digest).decode("ascii")


def sha256_src(data: bytes) -> str:
    return "sha256-" + b64(hashlib.sha256(data).digest())


def sha384_sri(data: bytes) -> str:
    return "sha384-" + b64(hashlib.sha384(data).digest())


def inline_script_hashes(html: str) -> list[str]:
    """SHA-256 of each inline <script> (those without a src= attribute)."""
    hashes = []
    for tag in re.finditer(r"<script\b([^>]*)>(.*?)</script>", html, re.S):
        if re.search(r"\bsrc\s*=", tag.group(1)):
            continue  # external module script — covered by script-src 'self'
        hashes.append(sha256_src(tag.group(2).encode("utf-8")))
    return hashes


def build_csp(script_hashes: list[str]) -> str:
    script_src = " ".join(["'self'"] + [f"'{h}'" for h in script_hashes])
    return "; ".join([
        "default-src 'none'",
        f"script-src {script_src}",
        "style-src 'self'",
        "img-src 'self'",
        "connect-src 'self'",
        "base-uri 'none'",
        "form-action 'none'",
        "frame-ancestors 'none'",
    ])


def set_integrity(html: str, target: str, value: str) -> str:
    """Add/replace integrity="…" on the tag that loads `target`."""
    # Match the single tag (link or script) whose href/src is this target.
    pat = re.compile(r"<(?:link|script)\b[^>]*\b(?:href|src)\s*=\s*[\"']"
                     + re.escape(target) + r"[\"'][^>]*>")
    m = pat.search(html)
    if not m:
        raise SystemExit(f"gen-csp: could not find a tag loading {target!r} in index.html")
    tag = m.group(0)
    inner = re.sub(r"\s+integrity\s*=\s*[\"'][^\"']*[\"']", "", tag)
    inner = inner[:-1].rstrip()               # drop the closing '>'
    self_closing = inner.endswith("/")
    if self_closing:
        inner = inner[:-1].rstrip()           # drop the '/' of a '/>' tag
    closer = " />" if self_closing else ">"
    patched = f'{inner} integrity="{value}"{closer}'
    return html[:m.start()] + patched + html[m.end():]


def render_headers(csp: str) -> str:
    lines = ["# Generated by tools/gen-csp.py — do not edit by hand.",
             "# Applies to Cloudflare Pages / any host that reads a _headers file.",
             "/*",
             f"  Content-Security-Policy: {csp}"]
    lines += [f"  {name}: {val}" for name, val in STATIC_HEADERS]
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    html = INDEX.read_text()

    script_hashes = inline_script_hashes(html)
    csp = build_csp(script_hashes)

    new_html = html
    sri = {}
    for target in SRI_TARGETS:
        value = sha384_sri((ROOT / target).read_bytes())
        sri[target] = value
        new_html = set_integrity(new_html, target, value)

    new_headers = render_headers(csp)
    old_headers = HEADERS.read_text() if HEADERS.exists() else ""

    changed = (new_html != html) or (new_headers != old_headers)

    if check:
        if changed:
            print("gen-csp: OUT OF DATE — run `python3 tools/gen-csp.py` and redeploy.")
            return 1
        print("gen-csp: index.html and _headers are up to date.")
        return 0

    INDEX.write_text(new_html)
    HEADERS.write_text(new_headers)

    print("Inline <script> hashes (script-src):")
    for h in script_hashes:
        print(f"  {h}")
    print("Subresource integrity (SRI):")
    for target, value in sri.items():
        print(f"  {target}: {value}")
    print(f"\nWrote {HEADERS.relative_to(ROOT)} and patched {INDEX.relative_to(ROOT)}"
          f" ({'updated' if changed else 'no change'}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
